// This file has been generated by chassis with the recipe react@0.0.1
// @see https://github.com/transcovo/chassis
//
// EDIT CAUTIOUSLY

module.exports = {
  roots: ['<rootDir>'],
  transform: {
    '^.+\\.ts?$': 'ts-jest',
  },
  testMatch: ['<rootDir>/**/__tests__/**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  collectCoverageFrom: ['src/**/*.ts', '!src/__tests__/**'],
  moduleNameMapper: {
    'yargs:': '<rootDir>/__tests__/__mocks__/yargs/index.ts',
  },
  globals: {
    'ts-jest': {
      tsConfig: '<rootDir>/tsconfig.json',
    },
  },
};
